cask_args appdir: '/Applications'

brew 'curl'
brew 'wget'
brew 'git'
brew 'git-crypt'
brew 'git-lfs'
brew 'z'
brew 'jq'
brew 'go'
brew 'node'
brew 'k3d'
brew 'kubernetes-cli'
brew 'kubie'
brew 'zsh-completions'

cask 'docker'
cask 'google-chrome'
cask 'iterm2'
cask 'virtualbox'
cask 'sublime-text'
cask 'visual-studio-code'
cask 'postman'
cask 'karabiner-elements'
cask 'spectacle'
